### PR TITLE
CMake: Export Wt package

### PR DESCRIPTION
**Pull request by podsvirov**
The IMPORTED targets:
- Wt::Wt
- Wt::Ext
- Wt::Test
- Wt::HTTP
- Wt::FCGI
- Wt::Isapi
- Wt::Dbo
- Wt::DboSqlite3
- Wt::DboPostgres
- Wt::DboFirebird
- Wt::DboMySQL

Usage in CMake project:
> find_package(Wt)
> add_executable(hello hello.cpp)
> target_link_libraries(hello Wt::HTTP)

Use the NEW behavior for the policy CMP0022
to export relocatable Config-file package

Use Boost IMPORTED targets if defined

Update minimum required CMake version to 2.8.12

### CODE REVIEW

**Comment by podsvirov** [comment]
Hello @kdeforche! Please review this PR.
This is the minimum workable implementation. Comments and suggestions are welcome.
After merging, we can think about adding a version check and the required components.

**Comment by podsvirov** [comment]
Cc: @emweb.

**Comment by podsvirov** [comment]
Also to make the CMake package relocatable, we need use only imported targets for PUBLIC dependencies
and use PRIVATE|PUBLIC|INTERFACE options with `target_link_libraries` commands.

**Comment by podsvirov** [comment]
I'm created create issue [#5768](http://redmine.emweb.be/issues/5768) at Redmine.
But now I could not modify it, because have not apropriate rights.
Any feedback please.

**Comment by podsvirov** [comment]
Reabsed to latest `master` and set `CMP0022` to `NEW` value.

**Comment by wdu** [comment]
Hi Konstantin,

I have played a bit with this, looks promising.

I was looking at an install on my windows system and noticed that some of the dependencies contain absolute paths. For example:
INTERFACE_LINK_LIBRARIES "ws2_32;mswsock;$<$<NOT:$<CONFIG:DEBUG>>:c:/openssl//lib/VC/ssleay32MD.lib>; .....

Ideally, I'd like to do the binary build of the windows release, which can then be packaged en shipped with all dependencies available from some relative folder tree. Do you have any experience with what to do to make these paths relative?

**Comment by podsvirov** [comment]
Hi @wdu, the PR forced updated. Please review again.

Changes:
> Use Boost IMPORTED targets if defined

Now for simple exemple like `hello world` it's should work:
> find_package(Wt)
> add_executable(hello hello.cpp)
> target_link_libraries(hello Wt::HTTP)

I test it with MinGW-w64 compiler on Windows. The my experimental installer [dad-0.3.1-windows-mingw64-unstable.exe](http://download.podsvirov.pro/installers/dad-0.3.1-windows-mingw64-unstable.exe).

**Comment by podsvirov** [comment]
@wdu, one question:
You really need CMake 2.4 compatibility?

**Comment by podsvirov** [comment]
Hm... @wdu, looks like current `master` is not CMake 2.4 compatibility.
I also had problems with version 2.6.
Only the latest version 2.8 is working.

**Comment by podsvirov** [comment]
About the installation in Windows.

I am the author of the CPack IFW generator.
For more information, refer to the [CPackIFW](https://cmake.org/cmake/help/latest/module/CPackIFW.html) module documentation.

Based on this generator, I develop a project to create a development environment.
For more information, visit the project website [DaD's House](https://dad.podsvirov.pro/house).

**Comment by wdu** [comment]
No, we didn't want to break it on purpose but I see no reason for keeping it if it bothers us.

**Comment by podsvirov** [comment]
Then my suggestion to increase the minimum used CMake version to 2.8.12:

* Functions for exporting and importing targets appeared in version 2.6
* In version 2.8.12, the targets configuration functions have been significantly improved.

These changes will simplify the export of the package and do not need to create crutches to support very old versions of the build system.

**Comment by podsvirov** [comment]
The PR forced updated.

Changes:
> Update minimum required CMake version to 2.8.12

Removed the code that was needed to ensure backward compatibility with older versions of the build system. Previous implementation [there](https://github.com/podsvirov/wt/tree/cmake-package-old-1).

**Comment by wdu** [comment]
I looked at the import files and there was a bit too much imported. I've added some PUBLIC's and PRIVATE's to TARGET_LINK_LIBRARIES in the Wt CMakeLists.txt files and this seems to resolve it (will be pushed to github soon).
I still have to check your latest changes.

**Comment by podsvirov** [comment]
I am glad to hear it. Be hesitant to make edits on top of my changes.
I like what you have started to distinguish between the public and private depending.
I guess that you are far the best I know the structure of the library.

**Comment by podsvirov** [comment]
Ping.

**Comment by emweb** [comment]
@wdu took a look at it, and it looks promising. I'll take a look at it too, see if we can put this in the final 3.3.8/4.0.0 release. @wdu is on vacation now, I'll discuss it with him when he gets back.

Regards,
Roel

**Comment by podsvirov** [comment]
I'm also on vacation :-)

**Comment by emweb** [comment]
Roel is working on including this in Wt 4.

Wim.

**Comment by emweb** [comment]
I didn't push this pull request as-is, but it is now in the wt4 branch.

**Comment by podsvirov** [comment]
@emweb, thanks for review and adding.
What is the probability of such changes occurring in the `master` branch (version 3)?

**Comment by wdu** [comment]
We were not planning on merging it in master. The modification is rather drastic for package maintainers etc, and I'd rather not include that in a minor version release, especially if we have the chance to introduce it in 4.0, which likely needs other modifications to packages too.

**Comment by podsvirov** [comment]
Okay, thanks for answer!

**Pull request closed without merging**
