### PR TITLE
CMake: Restore tests building

### PR DESCRIPTION
**Pull request by podsvirov**
These changes solve the problems that the linker now has.

### CODE REVIEW

**Comment by podsvirov** [comment]
I tested these changes on Windows with MinGW-w64-x86_64.

**Comment by podsvirov** [comment]
Hello @emweb and @wdu, please review this PR.

**Comment by podsvirov** [comment]
Apropriate [BUG#5873](https://redmine.webtoolkit.eu/issues/5873) at redmine.

**Comment by emweb** [comment]
This issue should have been resolved with commit 7af9793.

**Pull request closed without merging**
